[package]
name = "untamed_realms"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy= "0.11.0"
rand="0.8.5"
reqwest = {version = "0.11.18", features = ["json"]}

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
